### ISSUE TITLE
Add all-contributors plugin to improve README.md

### ISSUE THREAD

**Issue by LuckyPigeon** [101Loop/InstagramClone-FE#14]
## Is your feature request related to a problem? Please describe.

The contributor list in our `README.md` look like this now.
![image](https://user-images.githubusercontent.com/32315294/95581405-9014e900-0a6b-11eb-9e3d-0c3bfa5ae549.png)

I want to make it look like this.
![image](https://user-images.githubusercontent.com/32315294/95581466-ad49b780-0a6b-11eb-922a-2f3acf7a4d04.png)

## Describe the solution you'd like

Install a `github` plugin named `all-contributors`

Add contributors to contributor table using this query: `@all-contributors please add <user> for <task>`

Task label can refer to [this](https://allcontributors.org/docs/en/emoji-key)

## Describe alternatives you've considered

After we got over 100 stars, we can considered using `[opencollective](https://opencollective.com/)` as our solution, the UI of it will look like this.
![image](https://user-images.githubusercontent.com/32315294/95582701-94da9c80-0a6d-11eb-862d-67da50051253.png)

## Additional context

This operation requires maintainer or collaborator privilege, so could you consider add me as a collaborator?

**Comment by stephin007** [comment]
Hey, @LuckyPigeon I cannot give you this acess, due to some restrictions, BUt thankyou so much for your interest!
PLease checkout my profile, you can find many open source projects where you can contribute .
Would love to work with you more! 🎇

**Comment by LuckyPigeon** [comment]
@stephin007 
Hey, then I think you could improve `README.md` using this functionality by yourself, this could make it more interactive!

**Comment by stephin007** [comment]
Yes @LuckyPigeon Thankyou so much for your valuable suggestions.
Please mail me if you wanna collaborate more.

**Comment by LuckyPigeon** [comment]
@stephin007 
OK. I will mail you, my email will be `lucky90322@gmail.com`.

**Comment by stephin007** [comment]
mailed u @LuckyPigeon 😀
