### ISSUE TITLE
Need a Better UI for the front end

### ISSUE THREAD

**Issue by stephin007** [101Loop/InstagramClone-FE#4]
**Is your feature request related to a problem? Please describe.**
UI is not very good to look at since what mattered was the learning i got from the project, so now i  need some one to work on the ui of this clone

**Describe the solution you'd like**
Anyone reading this, please suggest some ui designs which you can implement

**Comment by karans5004** [comment]
Hi @stephin007, I will be working on making the UI more responsive and doing minor UI fixes as I go.
Pl suggest if you specifically need something implemented.

**Comment by stephin007** [comment]
Sure @karans5004 please do!
Send me some screenshots as you continue with work!

**Comment by stephin007** [comment]
@karans5004 please leave a 🌟 to the repo. it would be great!

**Comment by sujitIwale** [comment]
I can make some changes in UI could you assign me?

**Comment by stephin007** [comment]
Sure @sujitIwale Please go ahead

**Comment by stephin007** [comment]
@sujitIwale Now, i am confused when i checked you latesr PR, i had asked you to make a sepearte branch and push only the changes done for only the SignIn and SIgnUp and remove all other commits. Please do that accordingly.... I am closing all your PRs .please raise again accordingly! 😃

**Comment by LuckyPigeon** [comment]
@stephin007 @sujitIwale 
Is this Issue still going on?

**Comment by stephin007** [comment]
@LuckyPigeon Yes it is!

**Comment by stephin007** [comment]
Closing the issue, since we did not get any progress update from the commentors above

**Comment by LuckyPigeon** [comment]
@stephin007 
Do we need to update UI by using the code from #7?

**Comment by stephin007** [comment]
No please pull/fork the latest code, the UI is still the same @LuckyPigeon 
Are you gonna work in this, then only i ll reopen the issue!

**Comment by LuckyPigeon** [comment]
@stephin007 
Let me try the original code first, then I can decide wether I can do this issue.

**Comment by stephin007** [comment]
Let me know about the progress @LuckyPigeon

**Comment by LuckyPigeon** [comment]
@stephin007 
I've setup the site, I think I can give it a try.
