### ISSUE TITLE
Create an Interactive Readme.md

### ISSUE THREAD

**Issue by stephin007** [101Loop/InstagramClone-FE#5]
Anybody reading this, please give your input for creating a Readme.md
Will provide you the details.

**Comment by amy9032** [comment]
I can help with this, what should I do?

**Comment by stephin007** [comment]
Sure @amy9032 
Can you first show some example of readme.md which you will use!

**Comment by amy9032** [comment]
I will use another account(LuckyPigeon) for this PR.
I will use this [readme.md](https://github.com/line/armeria) for short content
And use this [readme.md](https://github.com/cdnjs/packages) for long content

**Comment by LuckyPigeon** [comment]
Hi @stephin007, I not very sure that I know what you try to achieved.
Could you be more detailed about how could I help with readme.md

**Comment by stephin007** [comment]
@LuckyPigeon May i know Why did you change account,? for this.

**Comment by stephin007** [comment]
@LuckyPigeon its an instagram clone which currently has the features like signin create post etc.
In future we will have features like liking the post, following other users etc.

And you can find the BACKEND repo in this same organization.

**Comment by LuckyPigeon** [comment]
@stephin007 
Actually, I maintain some of my school project using account amy9032 because it's a new account and I can make some github project contribution tutorial with it, and I will do the project contribution with this account, because this account feels more handy to me.

**Comment by LuckyPigeon** [comment]
@stephin007 
I found the backend repo, and have the basic concept of this.
Could you provide me the detail for the readme.md?
And does this repo has a slack or gitter so that I can update the progress immediately, or I could only use the github issue functionality to communicate.

**Comment by stephin007** [comment]
@LuckyPigeon
No as of now it doesn't have any slack connectedbut you can mail me at mail@stephinreji.me

**Comment by stephin007** [comment]
@LuckyPigeon any progress?

**Comment by LuckyPigeon** [comment]
@stephin007 
Could you provide me the details of what should I write in the reader.md. I have the template, but I don’t know where to start.
The "input" for creating a Readme.md you mentioned at the beginning, I assumed that is the template we've been talked before.
And the topic "Create an Interactive Readme.md", that means you want a program which receive the content and create a Readme.md automatically?
Pardon me, I have to know what should I do thoroughly, then I can get started.

**Comment by stephin007** [comment]
okay @LuckyPigeon , its an instagram clone Made on MERN stack, which features such us signin/signup/ create post /view posts of other people, etc
 This repo is for the front End, its made on React 

Its backend is built on Node ,express and MongoDB and you can find the back end in this same.organisation .

For setting up this repo , you need to first clone the back end and connect the database with Mongo.

And then you have to setup this repo for front end. 
- cd into client
- npm install
- npm start

The application will run on development server pointed to localhost:3000

**Comment by LuckyPigeon** [comment]
@stephin007 
Thank you for the information and the patience, I think I misunderstood what you are trying to say before, pardon me for that.
I know that now, and I'll begin working on it now, 
For the version 1 structure, I'll define as:
* Title
  <introduction>
* Table of Contents
* Requirement
* Contributing
  * Report Bugs
  * Fix Bugs
  * Implement Features
  * Submit Feedback
* How to Setup
  * Setup Backend
  * Setup Frontend
  * How to Create JWT Token
* Contributors
For the version 2, I'll try to update Contributors section's UI to this.
![image](https://user-images.githubusercontent.com/32315294/95091514-23db7200-0759-11eb-976c-621567f4e8da.png)
By the way, I'll send the preview screenshot as I finished.

**Comment by stephin007** [comment]
@LuckyPigeon Great! please continue.🤘🏿

**Comment by LuckyPigeon** [comment]
@stephin007 
I have finished, this is how it looks like.
![image](https://user-images.githubusercontent.com/32315294/95101136-66567c00-0764-11eb-82a1-399d2f59e491.png)
![image](https://user-images.githubusercontent.com/32315294/95100944-38713780-0764-11eb-9c40-565334e752e1.png)
![image](https://user-images.githubusercontent.com/32315294/95100961-3c04be80-0764-11eb-90d4-de7e31c5a47e.png)
![image](https://user-images.githubusercontent.com/32315294/95100971-3effaf00-0764-11eb-8a2e-90235aa2d138.png)

**Comment by stephin007** [comment]
@LuckyPigeon Its good , but few observations:
- change the text instagram clone-be to "Instagram Clone(BackEnd)"
- can you make it more interactive like adding emojis.
- Remove how to create jwt token section
- Remove dipanshu singh from contributers.

**Comment by LuckyPigeon** [comment]
@stephin007 
Done.
![image](https://user-images.githubusercontent.com/32315294/95112786-fbad3c80-0773-11eb-9c1c-8cbf2ef3a16f.png)
![image](https://user-images.githubusercontent.com/32315294/95112796-fea82d00-0773-11eb-8b96-60b88ed5d06c.png)
![image](https://user-images.githubusercontent.com/32315294/95112803-010a8700-0774-11eb-9b9a-dd04157bac33.png)
![image](https://user-images.githubusercontent.com/32315294/95112811-036ce100-0774-11eb-9f37-555a34fbb86e.png)

**Comment by stephin007** [comment]
Looking Good ;) @LuckyPigeon  please raise a PR from a different branch please dont push directly from master.
Your branch Naming convention should be:
**yourGithubName/<NewFeature, Enhancement, BugFix>/<messageforthefixyoudid>**
